# Generated by Django 2.2.3 on 2019-08-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calctool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='limit_point',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
