# Generated by Django 2.2.3 on 2019-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='func',
            field=models.CharField(max_length=100),
        ),
    ]
