# Generated by Django 2.2.3 on 2019-08-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_function_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='point',
            new_name='limit_point',
        ),
    ]
